### PR TITLE
Redirect to Reports app if Reports only permission

### PR DESCRIPTION
**Pull request by darushka**
CARD-7620
https://peachworks.leankit.com/card/716383643

### CODE REVIEW

**Comment by darushka** [comment]
@mbebas , do I need to update the https://github.com/getbeyond/ng-js-beyond-bootstrap package ?

**Comment by mbebas** [comment]
@darushka i will move it because i need to rebuild it anyway

**Comment by darushka** [comment]
Merged https://github.com/peachworks/ngPeachBootstrap/commit/b46e8dcb8f5ec34600f7f8c8413a4332bae441b2

**Comment by darushka** [comment]
v1.2.7

**Pull request closed without merging**
