### PR TITLE
Card 3979 always display the day parts page for account admins

### PR DESCRIPTION
**Pull request by PSkierniewski**
1. Added .idea to gitignore
2. Added setup section to readme
3. Changed Day Parts page logic to be visible only for admins and account owners

This branch resolves related issue:
https://peachworks.leankit.com/Boards/View/267929177/437845808

### CODE REVIEW

**Comment by darushka** [comment]
@PSkierniewski , can you please review your editor settings? We use 2 spaces indent and in your updates there are 4 spaces, isn't it?

**Comment by PSkierniewski** [comment]
@darushka Thanks for pointing that out, it's fixed now.

**Comment by mbebas** [comment]
@PSkierniewski please merge/squash

**Comment by PSkierniewski** [comment]
Merged at: 597987b73ff89b0444e308f715404e5dd7316d56

**Comment by mbebas** [comment]
v1.0.9

**Pull request closed without merging**
