### PR TITLE
check welcome app permission and unit tests

### PR DESCRIPTION
**Pull request by darushka**
This PR defines if Welcome App should be shown to user.

CARD-2866
https://peachworks.leankit.com/Boards/View/267929177/373005956

### CODE REVIEW

**Comment by mbebas** [comment]
:+1:

**Comment by PSkierniewski** [comment]
:+1:

**Comment by jsmylnycky** [comment]
@darushka please merge/squash this and ill get it ready for you to have available for the other parts

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/ngPeachBootstrap/commit/aa813b7532a5cdb0e51cad5eea272ca13fbb84b2

**Comment by jsmylnycky** [comment]
v1.0.7

**Pull request closed without merging**
