### PR TITLE
Card 1974 app reports not working in dev preview

### PR DESCRIPTION
**Pull request by darushka**
This PR fixes issue with app reports not being loaded in Dev Preview mode.

### CODE REVIEW

**Comment by rynomars** [comment]
👍

**Comment by jsmylnycky** [comment]
Please merge squash

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/ngPeachBootstrap/commit/6949ae648b4f327c75d0dc4bd8c24915406d7b8a

**Comment by jsmylnycky** [comment]
v1.0.4

**Pull request closed without merging**
