### PR TITLE
restricted Welcome App to be available for account admins

### PR DESCRIPTION
**Pull request by darushka**
This PR fixes issue with access to Welcome app by non admin users.

### CODE REVIEW

**Comment by jsmylnycky** [comment]
👍

**Comment by darushka** [comment]
@jsmylnycky , may I merge this one as part of welcome app update?

**Comment by jsmylnycky** [comment]
@darushka yes

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/ngPeachBootstrap/commit/1784aade9fa0a07b83239635f2907238763c4f3e

**Comment by jsmylnycky** [comment]
v1.0.8

**Pull request closed without merging**
