### PR TITLE
Added Employee page for accounts with has_employee pref set to true

### PR DESCRIPTION
**Pull request by darushka**
This PR updates sidenav for Employee mode.

### CODE REVIEW

**Comment by jsmylnycky** [comment]
Do me a favor and bump ngpeach to the latest.

**Comment by jsmylnycky** [comment]
:+1:

**Comment by rynomars** [comment]
:+1:

**Comment by mbebas** [comment]
:+1:

**Comment by jsmylnycky** [comment]
@darushka  please merge squash

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/ngPeachBootstrap/commit/7a95b82525883d5edbaf06fd68226bf88c0089bb

**Comment by jsmylnycky** [comment]
v1.0.3

**Pull request closed without merging**
