### PR TITLE
updated count of account reports

### PR DESCRIPTION
**Pull request by darushka**
This PR updates Sidenav to display correct count of All Reports and My Reports, as currently users have access to either their own account reports or those ones to which they have access via shared_roles.

CARD-2768
https://peachworks.leankit.com/Boards/View/267929177/367919756

### CODE REVIEW

**Comment by jsmylnycky** [comment]
👍

**Comment by mbebas** [comment]
:+1:

**Comment by darushka** [comment]
@jsmylnycky Can I merge this, as it needs for account reports updates testing on staging?

**Comment by jsmylnycky** [comment]
@darushka Go ahead... I'll get this out before the router stuff.

**Comment by darushka** [comment]
Merged https://github.com/peachworks/ngPeachBootstrap/commit/05c007b2fc63222d307b76d874a033f2f0ab86ce

**Comment by jsmylnycky** [comment]
v1.0.6

**Pull request closed without merging**
